#!C:/Program\ Files/Git/usr/bin/sh.exe

echo "Running ktlintFormat test..."

./gradlew ktlintFormat --daemon

status=$?

# return 1 exit code if running checks fails
[ $status -ne 0 ] && exit 1
exit 0